In [2]:
import numpy
import cv2

In [3]:
a = [0,1,2]

In [4]:
a[0:1]

[0]

In [5]:
a[0:2]

[0, 1]

In [8]:
im_g = cv2.imread("smallgray.png", 0) # 2 dimensional array. If we put '1' instead of '0', it will use 3 dimensional array (BGR)

In [9]:
print(im_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [10]:
im_g[0]

array([187, 158, 104, 121, 143], dtype=uint8)

In [11]:
im_g[1]

array([198, 125, 255, 255, 147], dtype=uint8)

In [12]:
im_g[2]

array([209, 134, 255,  97, 182], dtype=uint8)

In [13]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [15]:
im_g[0:2, 2:4] # same as in pandas. Before ',' are the rows, after ',' are the columns.

array([[104, 121],
       [255, 255]], dtype=uint8)

In [16]:
im_g.shape

(3, 5)

In [17]:
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [19]:
im_g[2,4] # very last value

182

In [20]:
for i in im_g: # iterate through rows
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [21]:
for i in im_g.T: # iterate through columns (Transpose it)
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [23]:
for i in im_g.flat: # iterate value through value one by one
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182
