In [1]:
#Numpy provides a multi-dimensional array object

In [2]:
import numpy

In [8]:
n = numpy.arange(27) # 1 dimensional array

In [4]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [7]:
n.reshape(3,9) # 2 dimensional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
n.reshape(3,3,3) # 3 dimensional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [10]:
m = numpy.asarray([[123,123,123,321,321],[],[]]) #convert a list to a numpy array

In [11]:
m

array([list([123, 123, 123, 321, 321]), list([]), list([])], dtype=object)

In [12]:
print(m)

[list([123, 123, 123, 321, 321]) list([]) list([])]


In [13]:
type(m)

numpy.ndarray

In [15]:
# OpenCV is image processing library